#!/bin/sh
s="conn_id=0&conn_mode=B&ipv=1&ipv6_origin=AutoConfigured&ipv6_prefix=PrefixDelegation&aftr_mode=0&aftr_addr=&ip_mode=dhcp&pppoe_username=&pppoe_password=&externalIpAddr=&netmask=&defGateway=&ipAddr_v6=&defGw_v6=&prefix_v6=&firstDns=&secondDns=&natSw=on&mtu=1500&dhcp_enable=on&vlanSw=2&vlanId=100&m8021p=1&servlist=INTERNET&tvid=&vport=1&svid=&vbindings=&act=&auth=factory"
export CONTENT_LENGTH=${#s} REQUEST_METHOD=POST CONTENT_TYPE=application/x-www-form-urlencoded  LD_LIBRARY_PATH=/webs/
echo $s | /webs/wan_config.cgi config

