#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org

START=99

start() {
    /usr/bin/apcloud_watchdog /etc/config/ apcloud_config.txt

    # Second watchdog :D
    hack_everything_ok_check.sh &

}

stop() {

    kill $(ps | grep /usr/bin/apcloud | grep -v grep | awk '{print $1}') 2>/dev/null
    killall hack_everything_ok_check.sh
}
