#!/bin/sh
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/dropbear
NAME=dropbear
DESC="Dropbear SSH server"

DROPBEAR_PORT=$1
DROPBEAR_idle_timeout=$2

if [ $DROPBEAR_PORT -ne 22 ]; then
DROPBEAR_EXTRA_ARGS="-R -p 22"
else
DROPBEAR_EXTRA_ARGS="-R"
fi

set -e

# test ! -h /var/service/dropbear || exit 0
mkdir -p /configs/dropbear
DROPBEAR_RSAKEY_DEFAULT="/configs/dropbear/dropbear_rsa_host_key"
DROPBEAR_DSSKEY_DEFAULT="/configs/dropbear/dropbear_dss_host_key"

test -z "$DROPBEAR_BANNER" || \
  DROPBEAR_EXTRA_ARGS="$DROPBEAR_EXTRA_ARGS -b $DROPBEAR_BANNER"
test -n "$DROPBEAR_RSAKEY" || \
  DROPBEAR_RSAKEY=$DROPBEAR_RSAKEY_DEFAULT
test -n "$DROPBEAR_DSSKEY" || \
  DROPBEAR_DSSKEY=$DROPBEAR_DSSKEY_DEFAULT
test -n "$DROPBEAR_KEYTYPES" || \
  DROPBEAR_KEYTYPES="rsa dsa"

gen_keys() {
for t in $DROPBEAR_KEYTYPES; do
  case $t in
    rsa)
        test -f $DROPBEAR_RSAKEY || dropbearkey -t rsa -f $DROPBEAR_RSAKEY
	;;
    dsa)
        test -f $DROPBEAR_DSSKEY || dropbearkey -t dss -f $DROPBEAR_DSSKEY
	;;
  esac
done
}

case "$3" in
  start)
	echo -n "Starting $DESC: "
	gen_keys
	KEY_ARGS=""
	test -f $DROPBEAR_DSSKEY && KEY_ARGS="$KEY_ARGS -r $DROPBEAR_DSSKEY"
	test -f $DROPBEAR_RSAKEY && KEY_ARGS="$KEY_ARGS -r $DROPBEAR_RSAKEY"
	start-stop-daemon -S \
	  -x "$DAEMON" -- $KEY_ARGS \
	    -p "$DROPBEAR_PORT" -I "$DROPBEAR_idle_timeout" $DROPBEAR_EXTRA_ARGS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON"
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon -K -x "$DAEMON"
	sleep 1
	KEY_ARGS=""
	test -f $DROPBEAR_DSSKEY && KEY_ARGS="$KEY_ARGS -r $DROPBEAR_DSSKEY"
	test -f $DROPBEAR_RSAKEY && KEY_ARGS="$KEY_ARGS -r $DROPBEAR_RSAKEY"
	start-stop-daemon -S \
	  -x "$DAEMON" -- $KEY_ARGS \
	    -p "$DROPBEAR_PORT" -I "$DROPBEAR_idle_timeout" $DROPBEAR_EXTRA_ARGS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
